"""
core/plagiarism_engine.py
-------------------------
ClassIQ Plagiarism and AI-Detection Engine.
Provides a heuristic-based probability score estimating if a response
was copy-pasted or generated by AI (ChatGPT/Claude/etc.).

Production systems use advanced embeddings or services like Turnitin/GPTZero.
This module uses a robust local heuristic approach mimicking such tools.
"""

import re

# Characteristic AI phrases often found in copy-pasted ChatGPT responses
AI_PHRASES = [
    r"in conclusion", r"it is important to note", r"it's important to note",
    r"as an ai", r"as a language model", r"delve into", r"moreover",
    r"furthermore", r"can be defined as", r"can be summarized as",
    r"crucial aspect", r"vital component", r"significant role",
    r"thus", r"consequently", r"therefore, we can see",
    r"to summarize", r"in summary", r"is a fascinating",
    r"let's dive into", r"let's break down", r"to begin with",
    r"it goes without saying", r"a myriad of", r"a tapestry of",
]


def _calculate_perplexity_proxy(text: str) -> float:
    """
    Very rough proxy for text perplexity (AI text tends to have lower variance 
    in word length and sentence structure compared to human text).
    Returns a score 0.0 - 1.0 (higher = more uniform/AI-like).
    """
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 5]
    if not sentences:
        return 0.0

    lengths = [len(s.split()) for s in sentences]
    avg_len = sum(lengths) / len(lengths)
    
    # Calculate variance
    variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)
    
    # AI models often have sentence length variance around 10-20. 
    # High variance (> 40) is more "human". Low variance (< 5) is also weird.
    if 5 <= variance <= 30:
        return 0.6  # Moderately AI-like uniformity
    elif variance > 40:
        return 0.1  # Very human-like variance
    else:
        return 0.3


def detect_plagiarism(response_text: str) -> tuple[float, str]:
    """
    Evaluate response for potential AI generation or copy-pasting.
    
    Returns
    -------
    (plagiarism_prob: float (0.0 - 1.0), flag_reason: str)
    """
    text = response_text.lower()
    words = text.split()
    word_count = len(words)
    
    if word_count < 10:
        return 0.0, "Too short to evaluate"

    score = 0.0
    reasons = []

    # 1. AI Phrase matching
    matched_phrases = 0
    for phrase in AI_PHRASES:
        if re.search(r'\b' + phrase + r'\b', text):
            matched_phrases += 1
            
    if matched_phrases >= 2:
        score += 0.4
        reasons.append(f"Contains characteristic AI phrases ({matched_phrases})")

    # 2. Structural Uniformity (Perplexity Proxy)
    perp_score = _calculate_perplexity_proxy(response_text)
    score += perp_score * 0.3
    if perp_score > 0.5:
        reasons.append("Unnatural sentence structure uniformity")

    # 3. Formatting artifacts (asterisks, bullet points copied from Markdown or Wikipedia citations)
    if "**" in response_text or "##" in response_text:
        score += 0.35
        reasons.append("Markdown formatting artifacts detected")
        
    if re.search(r'\[\d+\]', text) or "[edit]" in text or "retrieved from" in text:
        score += 0.8
        reasons.append("Copy-paste artifacts detected (Wikipedia/Web)")

    # 4. Length anomaly (perfectly structured long paragraphs without typos)
    if word_count > 100:
        if not re.search(r'\b(im|alot|kinda|sorta|idk|idkl)\b', text):
            # AI/Wikipedia rarely uses casual abbreviations; students often do or make typos
            score += 0.15
        
        # If it's very long and highly formatted but no topic keywords match, it's just a raw dump
        sentences = len(re.split(r'[.!?]+', text))
        if words and (sentences == 0 or word_count / max(1, sentences) > 25):
            score += 0.2
            reasons.append("Unnatural paragraph length")

    # 5. Generic definition style text
    if re.search(r'\bis defined as\b', text) or re.search(r'\brefers to\b', text):
         if word_count > 40:
             score += 0.15
             reasons.append("Generic textbook definition style")

    # Cap between 0 and 1
    final_prob = min(1.0, max(0.0, score))
    
    reason_str = " | ".join(reasons) if reasons else "Original text"
    if final_prob >= 0.7:
        reason_str = "🚨 " + reason_str
        
    return final_prob, reason_str
